DOCKER_IMAGE = bhr_ch10_server:latest

.PHONY: all
all: build docker

.PHONY: build
build: agent client server

.PHONY: agent
agent:

.PHONY: client
client:

.PHONY: server
server:


.PHONY: docker
docker:
	docker build -t $(DOCKER_IMAGE) .
